#PARA DECLARAR UN ATRIBUTO PRIVADA UTILIZAMOS DOS GUIONES BAJOS: self.__saldo
class Cuenta:
    def __init__(self,saldo):
        self.__saldo=saldo
    def mostrar_saldo(self):
        print("Saldo: ",self.__saldo)

cuenta1=Cuenta(2000)
cuenta1.mostrar_saldo()
#QUE PASA SI ESCRIBES ESTO?
print(cuenta1.__saldo)
#PYTHON GENERA UN ERROR, PORQUE ESE NOMBRE NO ESTA DISPONIBLE
#DIRECTAMENTE DE ESA FORMA

#AQUI HAY UN CONCEPTO IMPORTANTE
#PYTHON UTILIZA UN MECANISMO DENOMINADO name mangling
#POR EJEMPLO: --> self.__saldo
#INTERNAMENTE SE TRANSFORMA APROXIMADAMENTE EN:
#_Cuenta__saldo
#POR ESTA RAZON EL ATRIBUTO NO ACCEDE DE ESTA MANERA MEDIANTE
#cuenta1.__saldo

#EL OBJETIVO PRINCIPAL ES EVITAR ACCESOS ACCIDENTALES Y CONFLICTIVOS 
#DE NOMBRES ESPECIALMENTE EN LA HERENCIA
#TEN PRESENTE QUE NO DEBE DE ENTENDERSE COMO PRIVACIDAD ABSOLUTA

