#UN ATRIBUTO PROTEGIDO, SE ESCRIBE COLOCANDO UN GUION BAJO: self _saldo
class Cuenta:
    def __init__(self,saldo):
        self._saldo=saldo

cuenta1=Cuenta(1500)
print(cuenta1._saldo)

#TENER PRESENTE COMO FUNCIONA:
#_saldo COMUNICA LA INTENCION
#"ESTE ATRIBUTO DEBERIA TRATARSE COMO INTERNO Y NO MODIFICARSE"
#"DIRECTAMENTE FUERA DE LA CLASE O SUBCLASES"
#ADEMAS ES UNA CONVENCION DE PYTHON, NO UNA PROHIBICION ABSOLUTA