#CREAR UNA CLASE Y UN OBJETO
#CREANDO LA CLASE ESTUDIANTE
class Estudiante:
    pass
#CREAR UN OBJETO --> iNSTANCIA DE UNA CLASE
estudiante1=Estudiante()
#QUIERO VISUALIZAR EL OBJETO
print(estudiante1)        
#<__main__.Estudiante object at 0x0000020B121E4590>
#ESTO OCURRE POR QUE PYTHON ESTA MOSTRANDO LA REFERENCIA DEL OBJETO